name: Build site

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Setup PHP with composer v2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer:v2

    - name: Build theme
      run: |
        cd wp-content/themes/tomoveit
        npm install
        npm run prod

    - name: Cleanup
      run: |
        rm -rf .git .gitignore .github 
        cd wp-content/themes/tomoveit
        rm -rf config .babelrc .eslintrc.js .postcssrc.js package-lock.json package.json node_modules
      
    - name: rsync deployment to www-data user.
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzrog --rsync-path="sudo rsync" --delete --backup --backup-dir=${{ secrets.DEPLOY_REMOTE_BACKUP_DIR_TOREADIT_HBGTEST_SE }}/$GITHUB_SHA --chown=www-data:www-data --chmod=g+rw --exclude wp-config.php --exclude wp-content/uploads --exclude wp-content/plugins/advanced-custom-fields-pro
        path: .
        remote_path: ${{ secrets.DEPLOY_REMOTE_PATH_TOREADIT_HBGTEST_SE }}
        remote_host: ${{ secrets.DEPLOY_REMOTE_HOST_TOREADIT_HBGTEST_SE }}
        remote_user: ${{ secrets.DEPLOY_AWS_REMOTE_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}